name: Update MMDB Database

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: false

      - name: Download IPinfo CSV
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          curl -fsSL -o ipinfo_lite.csv.gz "https://ipinfo.io/data/ipinfo_lite.csv.gz?token=${IPINFO_TOKEN}"
          gunzip ipinfo_lite.csv.gz

      - name: Init and Run Go Script
        run: |
          go mod init mmdb-builder
          go mod tidy
          go run main.go

      - name: Get Current Date for Release
        run: |
          echo "SHORT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: "${{ env.SHORT_DATE }}"
          files: Country.mmdb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
